import { Router } from "express";
import healthRouter from "./health.js";
import authRouter from "./auth.js";
import usersRouter from "./users.js";
import companiesRouter from "./companies.js";
import purchaseRequestsRouter from "./purchase-requests.js";
import approvalsRouter from "./approvals.js";
import approvalRulesRouter from "./approval-rules.js";
import purchaseOrdersRouter from "./purchase-orders.js";
import notificationsRouter from "./notifications.js";
import auditLogsRouter from "./audit-logs.js";
import settingsRouter from "./settings.js";
import dashboardRouter from "./dashboard.js";
import receivingRouter from "./receiving.js";
import departmentsRouter from "./departments.js";
import prTypesRouter from "./pr-types.js";
import pembayaranRouter from "./pembayaran.js";
import leaveManagementRouter from "./leave-management.js";
import historyRouter from "./history.js";
import locationsRouter from "./locations.js";
import brandsRouter from "./brands.js";
import dutyMealsRouter from "./duty-meals.js";
import externalRouter from "./external.js";
import publicApiRouter from "./public-api.js";
import apiKeysRouter from "./api-keys.js";

const router = Router();

router.use(healthRouter);
router.use("/auth", authRouter);
router.use("/users", usersRouter);
router.use("/companies", companiesRouter);
router.use("/purchase-requests", purchaseRequestsRouter);
router.use("/approvals", approvalsRouter);
router.use("/approval-rules", approvalRulesRouter);
router.use("/purchase-orders", purchaseOrdersRouter);
router.use("/notifications", notificationsRouter);
router.use("/audit-logs", auditLogsRouter);
router.use("/settings", settingsRouter);
router.use("/dashboard", dashboardRouter);
router.use("/receiving", receivingRouter);
router.use("/departments", departmentsRouter);
router.use("/pr-types", prTypesRouter);
router.use("/pembayaran", pembayaranRouter);
router.use("/leave", leaveManagementRouter);
router.use("/history", historyRouter);
router.use("/locations", locationsRouter);
router.use("/brands", brandsRouter);
router.use("/duty-meals", dutyMealsRouter);
router.use("/external", externalRouter);
router.use("/v1", publicApiRouter);
router.use("/api-keys", apiKeysRouter);

export default router;
